GENOME: /scratch/mal456/TE-proj-reorg/TestisTEs2021/subworkflows/gte21-custom-genome/results/custom-genome/combined.fasta
GTF: /scratch/mal456/TE-proj-reorg/TestisTEs2021/subworkflows/gte21-custom-genome/results/custom-genome/combined.fixed.gtf
